project_id = "izmgzstdgoswlozinmyk"

[functions.test-multilogin-auth]
verify_jwt = false

[functions.check-multilogin-secrets]
verify_jwt = false

[functions.multilogin-profiles]
verify_jwt = false

[functions.multilogin-token-manager]
verify_jwt = false

[functions.mock-rpa-bot]
verify_jwt = false