
[build]
builder = "DOCKERFILE"
dockerfilePath = "rpa-bot/Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health"
healthcheckTimeout = 300

[env]
PYTHONUNBUFFERED = "1"
DISPLAY = ":99"
