
name: Deploy RPA Bot to Railway

on:
  push:
    branches: [ main, master ]
    paths:
      - 'rpa-bot/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Railway
        run: |
          echo "🚀 Автоматическое развертывание на Railway"
          echo "Railway автоматически подхватит изменения из GitHub"
          echo "Убедитесь что Railway проект связан с этим репозиторием"
